version: '2'
services:
  am-web-dev:
    build:
      context: ../
      dockerfile: dev-env/Dockerfile
      args:
        - service_name=${SERVICE_NAME}
    command: npm run start
    ports:
      - 8000:3000
      - 8001:3001
    volumes:
      - ..:/home/app/${SERVICE_NAME}
      - /home/app/${SERVICE_NAME}/node_modules

  




